name: tme
services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-pass
      - MONGO_INITDB_ROOT_USER_FILE=/run/secrets/mongo-root-user
    volumes:
      - db-data:/data/db
    secrets:
      - mongo-root-user
      - mongo-root-pass

  db-viewer:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER="db"
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
      - ME_CONFIG_MONGODB_ADMINUSERNAME_FILE=/run/secrets/mongo-root-user
      - ME_CONFIG_MONGODB_ADMINPASSWORD_FILE=/run/secrets/mongo-root-pass
    secrets:
      - mongo-root-user
      - mongo-root-pass


#networks:


volumes:
  db-data:
    name: ${DATABASE_VOLUME}

secrets:
  mongo-root-pass:
    file: ./secrets/mongo-root-pass.txt
  mongo-root-user:
    file: ./secrets/mongo-root-user.txt